---
- name: Шаг 2 - Создание виртуальных машин
  hosts: proxmox
  roles:
    - proxmox-vm
  vars:
    bridge_name: vmbr1
    vm_template_id: 666 # ID вашего шаблона Debian 13. Нужно что бы в шаблоне стоял пакет cloud-init и qemu-guest-agent
    ssh_key_file: ~/.ssh/id_rsa.pub  #/home/mshilov/.ssh/id_ed25519.pub берет  с сервера proxmox, куда его надо заранее положить! так как дальнейшее управление будет вестись с моего ноутбука 

