all:
  children:
    proxmox:                       # Группа компьютеров Proxmox
      hosts:
        proxmox-server:            # Один компьютер в этой группе
          ansible_host: 192.168.88.161   # Его IP адрес
          ansible_user: root             # Заходим как root
          
    vms:                            # Группа виртуальных машин
      hosts:
        vm1:                         # Первая виртуалка
          ansible_host: 10.10.1.10    # Её IP адрес
          
        vm2:                         # Вторая виртуалка
          ansible_host: 10.10.1.20    # Её IP адрес
        test:
          ansible_host: 10.10.1.40

      vars:
        ansible_user: max
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_become: yes
        ansible_become_method: sudo
        # 👇 ВСЕ VM подключаются через Proxmox
        ansible_ssh_common_args: '-o ProxyJump=root@192.168.88.161' #но так не сработает если ключ ноутбука не прокинут на конечные сервера. Потому что ProxyJump не выполняет последовательный вход сначала на PVE, а затем на ВМ. Он делает зашифрованный туннель до промежточного сервера и уже через этот туннель стучиться напрямую к конечному узлу!!! НО посколько у них нет ip связности то ключ надо прокидывать через сервер pve, используя следуюющую команду ssh-copy-id -o ProxyJump=root@192.168.88.161 max@10.10.1.40  ИЛИ же в роли proxmox-bridge задать копирование файла cloud-init конфигурации  
